#!/bin/bash
#Menu

opciones="Saludar Listar Salir"

select opcion in $opciones;
do
  if [ $opcion = "Saludar" ]; then
      echo "Hola desde Bash!"
  elif [ $opcion = "Listar" ]; then
      ls
  elif [ $opcion = "Salir" ]; then
      echo "Bye!"
      exit
  else
      echo "Opcion no permitida"
  fi
done
