#!/bin/bash
#Menu

opciones="Listar Salir"

select opcion in $opciones;
do
  if [ $opcion = "Listar" ]; then
      ls
  elif [ $opcion = "Salir" ]; then
      echo "Bye!"
      exit
  else
      echo "Opcion no permitida"
  fi
done
